name: Build macOS

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'Src/**'
      - 'version.txt'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'
          architecture: 'arm64'
          cache: 'pip'

      - name: Get Shortened Commit SHA
        id: shorten_commit_sha
        uses: iendeavor/shorten-commit-sha@v2.0.3
        with:
          length: 7

      - name: Create virtual environment
        run: python3 -m venv .venv

      - name: Activate virtual environment
        run: source .venv/bin/activate

      - name: Install dependencies
        run: pip install --upgrade -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --console --name "LinkYeeter" --clean --optimize "2" --strip --add-data "Src/get_addons.py:."  "Src/cli.py"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LinkYeeter-${{ steps.shorten_commit_sha.outputs.shortened_commit_sha }}-macOS-Arm64
          path: dist/LinkYeeter
