name: Build Windows

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'Src/**'
      - 'version.txt'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.10'
          architecture: 'x64'
          cache: 'pip'

      - name: Create virtual environment
        run: py -m venv .venv

      - name: Activate virtual environment
        run: .venv\Scripts\activate

      - name: Install dependencies
        run: pip install --upgrade requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --console --icon "Src/Icon/VALF.ico" --name "VALF" --clean --optimize "2" --version-file "version.txt" --add-data "Src/get_addons.py;." "Src/cli.py"   

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VALF-2.x.x-Windows-x64
          path: dist/VALF
